[WIP] Feature/add mustache views
sdonaghey03/dropwizard-rest-soap pull request #4
Opened 2017-05-24 15:59 UTC by sdonaghey03

2017-05-24 16:17 UTC, msjhall138 requested changes

2017-05-24 16:17 UTC, msjhall138 commented on src/main/java/com/kainos/example/jaxws/services/IThingService.java
Extra blank space

2017-05-24 16:17 UTC, msjhall138 commented on src/main/java/com/kainos/example/jaxws/services/IThingService.java
> +import com.kainos.example.jaxws.models.Thing;
Unused import

2017-05-24 16:17 UTC, msjhall138 commented on src/main/java/com/kainos/example/jaxws/services/ThingService.java
>  import com.kainos.example.jaxws.models.Thing;
Unused import

2017-05-25 09:38 UTC, msjhall138 requested changes

2017-05-25 09:38 UTC, msjhall138 commented on src/main/java/com/kainos/example/jaxws/services/ThingService.java
> +    @Override
Ditto above

2017-05-25 09:38 UTC, msjhall138 commented on src/main/java/com/kainos/example/jaxws/services/ThingService.java
>      @Override
Do not need override for interface implementation

2017-05-25 09:51 UTC, sdonaghey03 commented on src/main/java/com/kainos/example/jaxws/services/ThingService.java
>      @Override
To be debated

2017-05-25 09:52 UTC, msjhall138 commented on src/main/java/com/kainos/example/jaxws/services/ThingService.java
>      @Override
Grand - leave it for now

2017-05-25 09:52 UTC, sdonaghey03 commented
Changes implemented.

2017-05-25 09:53 UTC, msjhall138 approved these changes

2017-05-25 09:53 UTC, merged